// Assembles a finished reel from veo-prompt-template.md's own output.
//
//   every part   generated by Veo with the reference pack attached as referenceImages
//                (identity re-read fresh each call - no last-frame chaining, no drift)
//   final part   silent, ENVIRONMENT-only, the payoff shot the CTA lands on
//   CTA          composited onto the final part's own footage from its overlay_from
//                second to the end - not a separate card appended after the video
//
// There is no real-app screen-recording splice here. The reference pack's hero-phone.png
// already bakes the real Travafa UI into every generated frame that needs it, so a cutaway
// to actual screen-capture footage is no longer what makes the product look real.
//
// Usage: node build-reel.js <veo-prompt-output.md> <references.json> <out.mp4>

import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { GoogleGenAI } from "@google/genai";
import { cropTo9x16, concat, overlayLogo, overlayTimedPng, trimToLast } from "./video-lib.js";

const [, , promptPath, refsPath, out] = process.argv;
if (!promptPath || !refsPath || !out) {
  console.error("usage: node build-reel.js <veo-prompt-output.md> <references.json> <out.mp4>");
  process.exit(1);
}

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) { console.error("Missing GEMINI_API_KEY"); process.exit(1); }

const MODEL = process.env.VEO_MODEL || "veo-3.1-generate-preview";
const RESOLUTION = "1080p";   // 1080p only accepts 8s generations, which is all the template writes
const TMP = process.env.WORK_DIR || "prompts/_reel";
fs.mkdirSync(TMP, { recursive: true });

const text = fs.readFileSync(promptPath, "utf8");
const { images } = JSON.parse(fs.readFileSync(refsPath, "utf8"));
const REF_FILE = { CHARACTER: images.character, HERO_PHONE: images.hero_phone, ENVIRONMENT: images.environment };
for (const [role, file] of Object.entries(REF_FILE)) {
  if (!fs.existsSync(file)) throw new Error(`Missing ${role} reference: ${file}`);
}

// --- parse the template's own output format --------------------------------------------
// PART <n> OF <total> — <seconds>s — references: A, B, C
//   <prompt body, up to the next PART/CTA OVERLAY header>
// CTA OVERLAY
//   kicker: ... / headline: ... / button: ... / footnote: ... / overlay_from: ...

const partHeader = /^PART\s+(\d+)\s+OF\s+(\d+)\s*[—-]\s*([\d.]+)s\s*[—-]\s*references:\s*([A-Z_,\s]+)$/gm;
const headers = [...text.matchAll(partHeader)];
if (!headers.length) throw new Error("No PART headers found - is this gen-veo-prompt.js's raw output?");

const ctaHeaderMatch = text.match(/^CTA OVERLAY\s*$/m);
const bodyEnd = ctaHeaderMatch ? ctaHeaderMatch.index : text.length;

const scenes = headers.map((m, i) => {
  const start = m.index + m[0].length;
  const end = i + 1 < headers.length ? headers[i + 1].index : bodyEnd;
  return {
    n: Number(m[1]), total: Number(m[2]), duration_seconds: Number(m[3]),
    references: m[4].split(",").map((r) => r.trim()).filter(Boolean),
    scene_prompt: text.slice(start, end).trim(),
  };
});

const ctaBlock = (() => {
  if (!ctaHeaderMatch) return null;
  const chunk = text.slice(ctaHeaderMatch.index, text.search(/^MANIFEST\s*$/m) > -1 ? text.search(/^MANIFEST\s*$/m) : text.length);
  const field = (name) => (chunk.match(new RegExp(`^${name}:\\s*(.+)$`, "m")) || [, ""])[1].trim();
  const trimRaw = field("trim_final_part_to");
  return {
    kicker: field("kicker"), headline: field("headline"), button: field("button"),
    footnote: field("footnote"),
    trim_final_part_to: trimRaw ? Number(trimRaw) : null,  // null = keep full 8s
    overlay_from: Number(field("overlay_from") || 5),
  };
})();
if (!ctaBlock) throw new Error("No CTA OVERLAY block found in prompt output");

const trimSec = ctaBlock.trim_final_part_to;
console.log(`${scenes.length} parts, references: ${scenes.map((s) => s.references.join("+")).join(" | ")}`);
if (trimSec) console.log(`Final part will be trimmed to last ${trimSec}s (raw Veo clip is still 8s)`);

console.log(`CTA: "${ctaBlock.headline}" / "${ctaBlock.button}" from ${ctaBlock.overlay_from}s of the final part\n`);

// --- generate ----------------------------------------------------------------------------

const ai = new GoogleGenAI({ apiKey });
const mime = (f) => (path.extname(f).toLowerCase() === ".jpg" || path.extname(f).toLowerCase() === ".jpeg" ? "image/jpeg" : "image/png");
const asset = (file) => ({ image: { imageBytes: fs.readFileSync(file).toString("base64"), mimeType: mime(file) }, referenceType: "ASSET" });

async function generate(scene) {
  const referenceImages = scene.references.map((role) => {
    if (!REF_FILE[role]) throw new Error(`Unknown reference role "${role}" in PART ${scene.n}`);
    return asset(REF_FILE[role]);
  });
  const req = {
    model: MODEL, prompt: scene.scene_prompt,
    config: {
      aspectRatio: "9:16", resolution: RESOLUTION, durationSeconds: 8,
      // negativePrompt is rejected outright ("not supported in your use case") whenever
      // referenceImages is also set - the two are mutually exclusive on this API. Every
      // constraint that would have gone here is written into the prompt body itself,
      // positively, by the template instead (see WHAT THE VIDEO MODEL CAN ACTUALLY DO).
      referenceImages,
    },
  };
  let op = await ai.models.generateVideos(req);
  while (!op.done) {
    await new Promise((r) => setTimeout(r, 10000));
    op = await ai.operations.getVideosOperation({ operation: op });
  }
  if (!op.response?.generatedVideos?.length) throw new Error("no video: " + JSON.stringify(op).slice(0, 400));
  return op.response.generatedVideos[0].video;
}

const marked = [];
for (const scene of scenes) {
  const clean = `${TMP}/clean-${scene.n}.mp4`;
  if (fs.existsSync(clean) && process.env.RESUME === "1") {
    console.log(`part ${scene.n}/${scenes.length}  reusing existing clip`);
  } else {
    console.log(`part ${scene.n}/${scenes.length}  ${scene.duration_seconds}s  refs=${scene.references.join("+")}`);
    let video;
    for (let attempt = 1; attempt <= 3; attempt++) {
      try { video = await generate(scene); break; }
      catch (e) {
        console.log(`  attempt ${attempt} failed: ${String(e.message).slice(0, 140)}`);
        if (attempt === 3) throw e;
        await new Promise((r) => setTimeout(r, 5000 * 2 ** (attempt - 1)));
      }
    }
    const raw = `${TMP}/raw-${scene.n}.mp4`;
    await ai.files.download({ file: video, downloadPath: raw });
    console.log(`  crop: ${cropTo9x16(raw, clean) ?? "none"}`);
  }

  // For the final part: trim to last N seconds BEFORE logo/CTA overlay,
  // so the kept window is exactly what gets composited on.
  const isLast = scene.n === scenes.length;
  const clipForLogo = (isLast && trimSec)
    ? (() => {
        const trimmed = `${TMP}/trimmed-${scene.n}.mp4`;
        console.log(`  trim: keeping last ${trimSec}s of final part`);
        trimToLast(clean, trimmed, trimSec);
        return trimmed;
      })()
    : clean;

  const withLogo = `${TMP}/marked-${scene.n}.mp4`;
  overlayLogo(clipForLogo, withLogo);

  if (isLast) {
    // Final part: composite the CTA onto its own footage instead of appending a card.
    const png = `${TMP}/cta.png`;
    // The badge behind the logo is white, so the colour mark goes on it - the white
    // wordmark is for dark/photo backgrounds, and disappears on its own badge.
    execFileSync("python3", ["render_text.py", "cta", "assets/travafa-logo.png", png,
      ctaBlock.headline, ctaBlock.button, ctaBlock.kicker, ctaBlock.footnote], { stdio: "inherit" });
    const withCta = `${TMP}/final-with-cta.mp4`;
    overlayTimedPng(withLogo, png, withCta, ctaBlock.overlay_from);
    marked.push(withCta);
  } else {
    marked.push(withLogo);
  }
}

concat(marked, out);
const total = scenes.reduce((a, s) => a + s.duration_seconds, 0);
console.log(`\n${scenes.length} parts, ${total}s → ${out} (${(fs.statSync(out).size / 1e6).toFixed(2)} MB)`);
console.log("Video ends on the final part's own footage - no separate end card was appended.");
