// Assembles a finished reel from a prompt-layer output.
//
//   beats 1-3   generated by Veo, one scene each
//   beat 4      the real app, composited in one of three ways (demo_style)
//   beat 5      the end card, composited
//
// Veo runs at 720p here: three short beats need 4s scenes, and 1080p only produces 8s
// ones. cropTo9x16 upscales each clip to 1080x1920 afterwards, so the overlay geometry
// downstream stays in one coordinate system.
//
// Usage: node build-reel.js <prompt-output.json> <out.mp4> [demo_style_override]

import "dotenv/config";
import fs from "node:fs";
import { execFileSync } from "node:child_process";
import { GoogleGenAI } from "@google/genai";
import { cropTo9x16, lastFrame, concat, overlayLogo, appendEndCard } from "./video-lib.js";
import { demoCutaway, demoPip, demoScreenKeyed } from "./demo-composite.js";

const [, , src, out, styleOverride] = process.argv;
if (!src || !out) { console.error("usage: node build-reel.js <prompt-output.json> <out.mp4> [demo_style]"); process.exit(1); }

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) { console.error("Missing GEMINI_API_KEY"); process.exit(1); }

const MODEL = "veo-3.1-fast-generate-preview";
const RESOLUTION = "720p";
const TMP = process.env.WORK_DIR || "prompts/_reel";
fs.mkdirSync(TMP, { recursive: true });

const { dials, output } = JSON.parse(fs.readFileSync(src, "utf8"));
const scenes = output.scenes;
const style = styleOverride || dials.demo_style || "cutaway";

const DEMO_SECONDS = Number(process.env.DEMO_SECONDS || 5);
const CARD_SECONDS = Number(process.env.CARD_SECONDS || 3);
const RECORDING = process.env.RECORDING || "assets/app/rec-search-results.mp4";
// Whole-screen footage shrunk into an inset is unreadable, so the inset shows only the
// part worth reading. Full frame is fine for a cutaway, which fills the screen.
const REGION = style === "cutaway" ? { x: 0, y: 0.10, w: 1, h: 0.72 }
                                   : { x: 0.03, y: 0.30, w: 0.94, h: 0.40 };

const ai = new GoogleGenAI({ apiKey });

async function generate(prompt, seconds, startImage) {
  const req = {
    model: MODEL, prompt,
    config: {
      aspectRatio: "9:16", resolution: RESOLUTION, durationSeconds: seconds,
      negativePrompt: "on-screen text, captions, subtitles, watermarks, logos, brand names, " +
        "user interface elements, price tags, readable signage",
    },
  };
  if (startImage) req.image = { imageBytes: fs.readFileSync(startImage).toString("base64"), mimeType: "image/png" };
  let op = await ai.models.generateVideos(req);
  while (!op.done) {
    await new Promise((r) => setTimeout(r, 10000));
    op = await ai.operations.getVideosOperation({ operation: op });
  }
  if (!op.response?.generatedVideos?.length) throw new Error("no video: " + JSON.stringify(op).slice(0, 400));
  return op.response.generatedVideos[0].video;
}

const cleaned = [];
let handoff = null;

for (const [i, scene] of scenes.entries()) {
  const n = i + 1;
  const clean = `${TMP}/clean-${n}.mp4`;
  if (fs.existsSync(clean) && process.env.RESUME === "1") {
    console.log(`beat ${n}  reusing existing clip`);
    cleaned.push(clean);
    if (n < scenes.length) handoff = lastFrame(clean, `${TMP}/handoff-${n}.png`);
    continue;
  }
  const providedStart = scene.startImage || scene.start_image || null;
  const startInfo = providedStart ? ` startImage=${providedStart}` : (handoff ? `  ← continues` : "");
  console.log(`beat ${n}/${scenes.length}  ${scene.duration_seconds}s${scene.carries_dialogue ? "  (dialogue)" : ""}${startInfo}`);

  let video;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try { video = await generate(scene.scene_prompt, scene.duration_seconds, providedStart || handoff); break; }
    catch (e) {
      console.log(`  attempt ${attempt} failed: ${String(e.message).slice(0, 110)}`);
      if (attempt === 3) throw e;
      const wait = 5000 * 2 ** (attempt - 1);
      await new Promise((r) => setTimeout(r, wait));
    }
  }
  const raw = `${TMP}/raw-${n}.mp4`;
  await ai.files.download({ file: video, downloadPath: raw });
  console.log(`  crop: ${cropTo9x16(raw, clean) ?? "none"}`);
  cleaned.push(clean);
  if (n < scenes.length) handoff = lastFrame(clean, `${TMP}/handoff-${n}.png`);
}

// The watermark goes on generated footage only. On a full-frame shot of the app it
// lands on the app's own header and is redundant there anyway.
const marked = cleaned.map((clip, i) => {
  const m = `${TMP}/marked-${i + 1}.mp4`;
  overlayLogo(clip, m);
  return m;
});

const generatedSecs = scenes.reduce((a, s) => a + s.duration_seconds, 0);
let body = `${TMP}/body-${style}.mp4`;

if (style === "cutaway") {
  // The demo is its own shot and adds to the running time.
  const clip = demoCutaway(RECORDING, `${TMP}/demo-cutaway.mp4`, { seconds: DEMO_SECONDS, region: REGION });
  concat([...marked, clip], body);
} else {
  // pip and keyed play the demo inside the last beat, so they add no time.
  const last = marked[marked.length - 1];
  const lastSecs = scenes[scenes.length - 1].duration_seconds;
  const startAt = Math.max(0, lastSecs - DEMO_SECONDS);
  const withDemo = `${TMP}/last-${style}.mp4`;

  if (style === "pip_overlay") {
    demoPip(last, RECORDING, withDemo, { seconds: DEMO_SECONDS, startAt, side: "right", widthPct: 0.40, region: REGION });
  } else {
    // Fixed rectangle: the system prompt requires the phone to be held still for this
    // style, which is what makes a per-frame track unnecessary.
    const rect = JSON.parse(process.env.SCREEN_RECT || '{"x":380,"y":880,"w":300,"h":640}');
    demoScreenKeyed(last, RECORDING, withDemo, {
      seconds: DEMO_SECONDS, startAt, screenRect: rect,
      keyColour: process.env.KEY_COLOUR || null,
    });
  }
  concat([...marked.slice(0, -1), withDemo], body);
}

const cardBg = lastFrame(body, `${TMP}/card-bg.png`);
const cardPng = `${TMP}/endcard-${style}.png`;
execFileSync("python3", ["make-endcard.py", cardBg, "assets/travafa-logo-white.png", cardPng,
  process.env.END_CARD_TEXT || "Book your trips now"], { stdio: "inherit" });
appendEndCard(body, cardPng, CARD_SECONDS, out);

const total = (style === "cutaway" ? generatedSecs + DEMO_SECONDS : generatedSecs) + CARD_SECONDS;
console.log(`\n${style}: ${scenes.length} beats ${generatedSecs}s + demo ${DEMO_SECONDS}s + card ${CARD_SECONDS}s = ${total}s → ${out} (${(fs.statSync(out).size / 1e6).toFixed(2)} MB)`);
